version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ../api
      target: dev
    volumes:
      - ../api:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    command: sleep infinity

  matchmaker:
    build:
      context: ../matchmaker
      target: dev
    volumes:
      - ../matchmaker:/workspace
      - /workspace/node_modules
    ports:
      - "4000:4000"
    command: sleep infinity
